POST http://localhost:3000/api/services
Content-Type: application/json

  {
    "name": "Decoração",
    "description": "Escolha a decoração para sua festa, e nós a montamos.",
    "price": 1400,
    "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
  }

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/67d850e76c64ccdbe6fdb90d

###
DELETE http://localhost:3000/api/services/67d850e76c64ccdbe6fdb90d

###
PUT http://localhost:3000/api/services/67d8527e34c4b4935d3ae127
Content-Type: application/json

{
    "name": "TESTE ATUALIZAÇÃO",
    "description": "Alguma descrição",
    "price": 2500,
    "image": "https://i.pinimg.com/1200x/d0/5a/52/d05a52d68dc2faa9e6cbdc538a8f250d.jpg"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Dominó",
    "author": "Caio Bertoldo",
    "description": "Dominó na casa do Isaac",
    "budget": 2000,
    "image": "https://i.pinimg.com/1200x/d0/5a/52/d05a52d68dc2faa9e6cbdc538a8f2",
    "services": [
        {
            "name": "Algum serviço 01",
            "description": "lepo lepo",
            "price": 3000,
            "image": "https://i.pinimg.com/1200x/d0/5a/52/d05a52d68dc2faa9e6cbdc538a8f250d.jpg"
        },
        {
            "name": "Algum serviço 02",
            "description": "bla bla",
            "price": 1600,
            "image": "https://i.pinimg.com/1200x/d0/5a/52/d05a52d68dc2faa9e6cbdc538a8f250d.jpg"
        }
    ]
}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/67d8660bc56de91ee36addc6

###
DELETE  http://localhost:3000/api/parties/67d8660bc56de91ee36addc6

###
PUT http://localhost:3000/api/parties/67d866dac56de91ee36addc8
Content-Type: application/json

{
    "title": "Dominó 2",
    "author": "Isaac Anijar",
    "description": "Dominó na casa do Isaac",
    "budget": 10000,
    "image": "https://images.pexels.com/photos/1205650/pexels-photo-1205650.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "services": [
        {
            "name": "Algum serviço 01",
            "description": "lepo lepo",
            "price": 3000,
            "image": "https://images.pexels.com/photos/1205650/pexels-photo-1205650.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
        {
            "name": "Algum serviço 02",
            "description": "bla bla",
            "price": 1600,
            "image": "https://images.pexels.com/photos/1205650/pexels-photo-1205650.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        }
    ]
}